### ISSUE TITLE
error in aberration if modulation == False

### ISSUE THREAD

**Issue by ajvanengelen** [amaurea/enlib#43]
Hi, I am trying to run the aberration routine with modulation turned off, and am finding the following:

/global/u2/e/engelen/enlib/aberration.py in aberrate(imap, dir, beta, mode, order, recenter, modulation)
     50         # import pdb
     51         # pdb.set_trace()
---> 52         omap *= pos[2+pol,None]
     53         return omap
     54 

IndexError: index 3 is out of bounds for axis 0 with size 3

**Comment by amaurea** [comment]
I've added an argument to make modulation optional now. Does this help?

**Comment by ajvanengelen** [comment]
Looks like it worked!  Not sure why it didn't work when I tried to do the same thing, but am glad this is working now.  Thanks!
