### ISSUE TITLE
For a patch, curved sky raw power spectrum is biased at low ells.

### ISSUE THREAD

**Issue by dwhan89** [amaurea/enlib#47]
I took raw power spectrum of a masked patch (ActPol D56 cutout)  once with flat-sky routine and again with enlib curved sky routine. I found a large deviation of curved-sky power spectrum at low ells compared to flat-sky power spectrum. You can see the similar feature if you just take raw power spectrum of the mask itself. Both the map and the mask are in CAR projection. 

------

### Raw specra (TT)

<img align='center' src="http://www.cosmo.bnl.gov/www/dwhan89/d56_raw_spec/tt_spec.png" alt="D56 T Spec" width="60%" />

### Curved sky PS vs. Flat sky PS (TT)

<img align='center' src="http://www.cosmo.bnl.gov/www/dwhan89/d56_raw_spec/tt_spec_frac_diff.png" alt="D56 T Frac" width="60%" />

------
### Masked D56 patch
<img align='center' src="http://www.cosmo.bnl.gov/www/dwhan89/d56_raw_spec/imap.png" alt="D56 T Map" width="90%" />

------
### The code snippet used to obtain curved sky power spectra 

```python
############ fsky ###################
def get_fsky(emap):
    area = emap.area() #in rad sq#
    fsky = area / (4.*np.pi)
    return fsky


############ spectra ################
def get_spectra(emap1, emap2=None, lmax=5000, normalize=True):
    alm1 = curvedsky.map2alm(emap1, lmax=lmax).astype(np.complex128)
    alm2 = alm1 if emap2 is None else curvedsky.map2alm(emap2, lmax=lmax).astype(np.complex128)

    cl  = hp.alm2cl(alm1, alm2, lmax=lmax)
    l   = np.arange(len(cl))

    if normalize:
        fsky  = get_fsky(emap1)
        cl    /= fsky
    else: pass
    return (l, cl)
```

**Comment by dwhan89** [comment]
Just for an extra bit of information. Here are average curved-sky spectra from sims vs the input theory if I undo the window induced coupling. You can still see the excess at low ells. 

<img align='center' src="http://www.cosmo.bnl.gov/www/dwhan89/d56_raw_spec/081518_dltt_ar2d56_frac_diff.png" alt="D56 T Frac" width="90%" />

**Comment by msyriac** [comment]
1) Couldn't the difference be from the way you are binning curved vs flat? They are not always comparable right?
2) What does the curved sky PS look like on the full sky without a mask? Does the same binning then agree with input theory?
3) What if you used a white noise spectrum in all the above plots?

**Comment by dwhan89** [comment]
Hey, Mat 

1. Couldn't the difference be from the way you are binning curved vs flat? They are not always comparable right?

I tried to match them as close as I could. But you are right, they are not 100% comparable. In particular, for flat-sky code, you have to collapse 2D power into 1D power before binning. Also, curved sky routine picks up all interger modes starting at l=0 up to l=lmax. For flat-sky code, you have some missing modes, and modes are not necessary at every interger. 

```python
class bin2D(object):
    def __init__(self, modlmap, bin_edges, right=True):
        self.centers = (bin_edges[1:]+bin_edges[:-1])/2.
        self.digitized = np.digitize(np.ndarray.flatten(np.array(modlmap)), bin_edges, right)
        self.bin_edges = bin_edges
    def bin(self,data2d):
        data = np.ndarray.flatten(np.array(data2d))
        return self.centers,np.array([np.nanmean(data[self.digitized == i]) for i in range(1, len(self.bin_edges))])


class bin1D(object):
    def __init__(self, l, bin_edges, right=True):
        self.centers = (bin_edges[1:]+bin_edges[:-1])/2.
        self.digitized = np.digitize(l, bin_edges, right)
        self.bin_edges = bin_edges
    def bin(self,data):
        return self.centers,np.array([np.nanmean(data[self.digitized == i]) for i in range(1, len(self.bin_edges))])
```
2. What does the curved sky PS look like on the full sky without a mask? Does the same binning then agree with input theory?

Full sky without a mask works very well. I didn't see any bias for full sky sims for any type of binning I tried.

3. What if you used a white noise spectrum in all the above plots?

I will try that. I doubt it will help with the bias below ell < 400. 
------

As we have discussed offline, the next step is to compare a spectrum from a D56 cutout from a full sky sim and a spectrum from the full sky sim with the region external to D56 masked out. I will report back.

**Comment by msyriac** [comment]
Hi @dwhan89 , did this get resolved with the Dl space binning?

**Comment by dwhan89** [comment]
Yes, it did. I am closing the issue.
