### ISSUE TITLE
Downsampling enplots

### ISSUE THREAD

**Issue by msyriac** [amaurea/enlib#7]
I tried to improve my wrapper around enplot to downsample before saving a high-resolution plot as you suggested with the `-d` option. See line 33 here:

https://github.com/msyriac/orphics/blob/master/orphics/tools/io.py#L21

But that doesn't seem to do anything; the plots are still full resolution. Do you know what's going on?

**Comment by aiolasimone** [comment]
`enplot.draw_map_field()` does not read the argument `-d`, even if correctly parsed. The downgrading is done while reading the `ifile`, which you bypass.

I would suggest:

```
def highResPlot2d(array,outPath,down=1,verbose=True,overwrite=True):
    if not(overwrite):
        if os.path.isfile(outPath): return
    try:
        from enlib import enmap, enplot
    except:
        printC("Could not produce plot "+outPath+". High resolution plotting requires enlib, which couldn't be imported. Continuing without plotting.",color='fail')
        return
        
 
    img = enplot.draw_map_field(enmap.downgrade(enmap.enmap(array)[None], down),enplot.parse_args("-vvvg moo"))
    img.save(outPath)
    if verbose: print bcolors.OKGREEN+"Saved high-res plot to", outPath+bcolors.ENDC
```
@amaurea may have a better solution.

**Comment by msyriac** [comment]
Cool, this works. Closing.
